# Generated by Django 5.2.8 on 2025-11-29 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=20, unique=True, verbose_name='학번')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('department', models.CharField(max_length=50, verbose_name='학과')),
                ('gender', models.CharField(max_length=10, verbose_name='성별')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='과목명')),
                ('professor', models.CharField(blank=True, max_length=50, verbose_name='담당 교수')),
                ('textbook', models.CharField(blank=True, max_length=100, verbose_name='교재명')),
                ('class_time', models.CharField(blank=True, max_length=50, verbose_name='수업 시간')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='점수')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='student_app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='student_app.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
